UniversityMVS/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectModels.Interface;
using System.Linq;


namespace UniversityMVS.Controllers
{
    public class CourseController:Controller
    {
        private ICourseRepository _repository;
        public CourseController(ICourseRepository repository)
        {
            _repository = repository;
        }

        public IActionResult GetCourses()
        {

            return View(_repository.GetAllCourses().ToList());
        }
    }
}

UniversityMVS/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectModels.Interface;
using System.Linq;
using UniversityMVS.Models;

namespace UniversityMVS.Controllers
{
    public class GroupController:Controller
    {
        private IGroupRepository _repositoryGroup;
        private IStudentRepository _repositoryStudent;

        public GroupController(IGroupRepository groupRepository, IStudentRepository studentRepository)
        {
            _repositoryGroup = groupRepository;
            _repositoryStudent = studentRepository;
        }
        public IActionResult GetGroup(int id)
        {
            return View(_repositoryGroup.GetGroupFromCourses(id).ToList());
        }

        [HttpGet]
        public IActionResult UpdateGroup(int id)
        {
            var item = _repositoryGroup.GetGroup(id);

            return View(item);
        }
        [HttpPost]
        public IActionResult UpdateGroup(Group group)
        {
            _repositoryGroup.UpdateGroup(group);

            return RedirectToAction("GetGroup", new {id = group.CourseId});
        }

        public IActionResult DeleteGroup(int id)
        {
            if (_repositoryStudent.CheckStudentFromGroup(id))
            {
                var exceptionText = "The group has students, group cannot be deleted!";
                return RedirectToAction("ExceptionGroup", "UserException", new {exception = exceptionText });
            }
            var item = _repositoryGroup.GetGroup(id);

            _repositoryGroup.DeleteGroup(id);
            return RedirectToAction("GetGroup", new { id = item.CourseId });
        }

        public IActionResult ExceptionDelete()
        {
            return View();
        }
    }
}

UniversityMVS/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectModels.Interface;
using System.Linq;
using UniversityMVS.Models;

namespace UniversityMVS.Controllers
{
    public class StudentController:Controller
    {
        private IStudentRepository _repository;

        public StudentController(IStudentRepository repository)
        {
            _repository = repository;
        }

        public IActionResult GetStudent(int id)
        {
            return View(_repository.GetStudentFromGroup(id).ToList());
        }
        [HttpGet]
        public IActionResult UpdateStudent(int id)
        {
            var item = _repository.GetStudent(id);

            return View(item);
        }

        [HttpPost]
        public IActionResult UpdateStudent(Student student)
        {
            _repository.UpdateStudent(student);

            return RedirectToAction("GetStudent", new { id = student.GroupId});
        }
    }
}

UniversityMVS/Controllers/UserExceptionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UniversityMVS.Controllers
{
    public class UserExceptionController:Controller
    {
        public IActionResult ExceptionGroup(string exception)
        {
            ViewBag.Message = exception;
            return View();
        }
    }
}

UniversityMVS/Views/Course/GetCourses.cshtml
@model List<Course>

    <div class="container">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">CourseName</th>
                    <th scope="col">Chose course</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var element in Model) 
                {
                    <tr>
                        <th scope="row">@element.Id</th>
                        <td>@element.Name</td>
                        <td><a class="btn btn-warning" asp-controller="Group" asp-action="GetGroup" asp-route-id="@element.Id">Select</a></td>
                    </tr>
                }
            </tbody>
        </table>        
    </div>

UniversityMVS/Views/Group/GetGroup.cshtml
@model List<Group>


<div class="container">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">CourseName</th>
                <th scope="col">GroupName</th>
                <th scope="col">Chose Group</th>
                <th scope="col">Edit Group</th>
                <th scope="col">Delete Group</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var element in Model)
            {
            <tr>
                <th scope="row">@element.Id</th>
                <td>@element.Course.Name</td>
                <td>@element.Name</td>
                <td><a class="btn btn-warning" asp-controller="Student" asp-action="GetStudent" asp-route-id="@element.Id">Select</a></td>
                <td><a class="btn btn-warning" asp-controller="Group" asp-action="UpdateGroup" asp-route-id="@element.Id">Edit</a></td>
                <td><a class="btn btn-warning" asp-controller="Group" asp-action="DeleteGroup" asp-route-id="@element.Id">Delete</a></td>
            </tr>
            }
        </tbody>
    </table>
</div>

UniversityMVS/Views/Group/UpdateGroup.cshtml
@model UniversityMVS.Models.Group

    <form asp-action="UpdateGroup" asp-controller="Group" asp-route-id="@Model.Id">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <input type ="hidden" asp-for="CourseId" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </form>

UniversityMVS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UniversityMVS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
</head>
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <a class="navbar-brand">University</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/Course/GetCourses">Courses<span class="sr-only"></span></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="container mt-5">
            @RenderBody()
        </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>
    </body>
</html>

UniversityMVS/Views/Student/GetStudent.cshtml
@model List<Student>

<div class="container">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">GroupName</th>
                <th scope="col">StudentName</th>
                <th scope="col">Edit Student</th>
                <th scope="col">Delete Student</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var element in Model)
            {
                <tr>
                    <th scope="row">@element.Id</th>
                    <td>@element.Group.Name</td>
                    <td>@element.Name</td>
                    <td><a class="btn btn-warning" asp-controller="Student" asp-action="UpdateStudent" asp-route-id="@element.Id">Edit</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

UniversityMVS/Views/Student/UpdateStudent.cshtml
@model UniversityMVS.Models.Student

    <form asp-action="UpdateStudent" asp-controller="Student" asp-route-id="@Model.Id">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="GroupId" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </form>

UniversityMVS/Views/UserException/ExceptionGroup.cshtml
<h1>
    @ViewBag.Message
</h1>

<input type="button" onclick="history.go(-1)" value="Return" />